image: node:latest

stages:
  - Build
  - Test
  - Deploy

cache:
  paths:
    - zod/node_modules/

Install Dependencies:
  stage: Build
  script:
    - cd zod
    - yarn install
  artifacts:
    paths:
      - zod/node_modules/

Build:
  stage: Build
  script:
    - cd zod
    - tsc

Test:
  stage: Test
  script:
    - cd zod
    - yarn test

Deploy:
  stage: Deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "master"
  only:
    - tags
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$REGISTRY_USER\",\"password\":\"$REGISTRY_PW\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
