image: timbru31/ruby-node

stages:
  - Build
  - Test
  - Deploy

cache:
  paths:
    - zod/node_modules/

Install Dependencies:
  stage: Build
  script:
    - cd zod
    - yarn install
    
Build:
  stage: Build
  script:
    - cd zod
    - ./node_modules/typescript/bin/tsc

Test:
  stage: Test
  script:
    - cd zod
    - mv .env.example .env
    - yarn test

Upload tarbells:
  stage: Deploy
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "master"
  only:
    - tags
  script:
    - cd zod
    - apt-get update
    - apt-get install rename -y
    - yarn global add @oclif/dev-cli
    - oclif-dev pack --no-xz --targets=
    - mv ./dist/zod* ./dist/zod
    - cd ./dist/zod
    - rename 's/zod-(v)(\d+\.)(\d+\.)(\d+)/zod/gi' *.tar.gz
    - mv ../../.env.example ./dist/zod/.env
    - gem install dpl
    - dpl --skip_cleanup --provider=s3 --access_key_id=$DIGITAL_OCEAN_ACCESS_KEY_ID --secret_access_key=$DIGITAL_OCEAN_SECRET_ACCESS_KEY --bucket=xura-cdn --region=sfo2 --endpoint=https://sfo2.digitaloceanspaces.com --local_dir=./ --upload_dir=zod --acl=public_read

Build Docker Image:
  stage: Deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "master"
  only:
    - tags
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$REGISTRY_USER\",\"password\":\"$REGISTRY_PW\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
