- name: Create {{stagingHtdocs}}
  file:
    path: "{{stagingHtdocs}}"
    state: directory

- name: Download SPA index.html file for project
  get_url:
    url: "{{indexHtmlCdnUrl}}"
    dest: "{{stagingHtdocs}}"

- name: Remove SPA Container if exists
  docker_container:
    name: "{{containerName}}"
    state: absent
    force_kill: yes

- name: Spin up SPA Container
  docker_container:
    name: "{{containerName}}"
    image: httpd:alpine
    env:
      LETSENCRYPT_HOST: "{{containerName}}"
      LETSENCRYPT_EMAIL: joe307bad@gmail.com
      VIRTUAL_HOST: "{{containerName}}"
    expose:
      - 80
    volumes:
      - "{{stagingHtdocs}}:/usr/local/apache2/htdocs"
    networks:
      - name: "{{network}}"
    network_mode: bridge
  tags: spa-container