- name: Destroy SPA Container
  docker_container:
    name: "{{item}}"
    state: absent
  with_items:
  - "{{containerNames}}"

- name: Destroy htdocs
  file:
    path: "{{item}}"
    state: absent
  with_items:
  - "{{stagingHtdocs}}"

- name: Destroy SSL certs
  shell: rm -rf "{{item}}"
  with_items:
  - "{{certsFilesAndFolders}}"

- name: Remove SSL cert directory content
  file:
    path: "{{item}}" 
    state: absent
  with_items: "{{certDirs}}"