export const DIGITAL_OCEAN_ACCESS_KEY_ID =
  process.env.DIGITAL_OCEAN_ACCESS_KEY_ID
export const DIGITAL_OCEAN_SECRET_ACCESS_KEY =
  process.env.DIGITAL_OCEAN_SECRET_ACCESS_KEY
export const DIGITAL_OCEAN_BUCKET_NAME = process.env.DIGITAL_OCEAN_BUCKET_NAME
export const DIGITAL_OCEAN_ENDPOINT = process.env.DIGITAL_OCEAN_ENDPOINT
export const DIGITAL_OCEAN_REGION = process.env.DIGITAL_OCEAN_REGION
